version: "3.9"

services:
  app:
    build: .
    env_file: server/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      # Persist uploaded files between container restarts
      - uploads:/app/server/uploads

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: capuser
      POSTGRES_PASSWORD: cap_pw
      POSTGRES_DB: capdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  uploads: 