version: '3.8'

services:
  postgres-local:
    image: postgres:15
    container_name: civicbridge-postgres-local
    environment:
      POSTGRES_DB: civicbridgepulse_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_local_data: 